# Generated by Django 4.1.6 on 2023-02-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
