# Generated by Django 4.1.6 on 2023-02-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_image_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='num',
        ),
    ]
